### ISSUE TITLE
Availability of code

### ISSUE THREAD

**Issue by arkadaw9** [edwardyehuang/CAA#1]
Very interesting work. Is the code publicly available?

**Comment by edwardyehuang** [comment]
> 
> 
> Very interesting work. Is the code publicly available?

Thanks for your interest! Currently, our work is in peer-review, and full code, configs, and ckpts will be available publicly after being accepted. 

I will keep this issue open until it happens.

**Comment by edwardyehuang** [comment]
Code will be uploaded in recent weeks
